name: Teste de Senha

on:
  push:
    branches:
      - teste

jobs:
  teste-senha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configuração do Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8



    - name: Executar Teste de Senha
      run: python main.py
